name: sam3
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.6
  - pip:
      - sam3
      - ultralytics
      - opencv-python
      - numpy
      - matplotlib
      - scipy
      - scikit-image
      - scikit-learn
      - pandas
      - decord
      - einops
      - timm
      - tensorboard
